# Generated by Django 3.2.5 on 2021-08-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
